"""empty message

Revision ID: 285e883422a7
Revises: 164da5ec88e5
Create Date: 2026-09-10 15:29:08.961239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '285e883422a7'
down_revision: Union[str, Sequence[str], None] = '164da5ec88e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_lab_details', 'reference_file_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    for fk in sa.inspect(op.get_bind()).get_foreign_keys('task_lab_details'):
        if fk['constrained_columns'] == ['reference_file_id']:
            op.drop_constraint(fk['name'], 'task_lab_details', type_='foreignkey')
    op.create_foreign_key(None, 'task_lab_details', 'files', ['reference_file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for fk in sa.inspect(op.get_bind()).get_foreign_keys('task_lab_details'):
        if fk['constrained_columns'] == ['reference_file_id']:
            op.drop_constraint(fk['name'], 'task_lab_details', type_='foreignkey')
    op.create_foreign_key(op.f('task_lab_details_ibfk_1'), 'task_lab_details', 'files', ['reference_file_id'], ['id'])
    op.alter_column('task_lab_details', 'reference_file_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
