"""empty message

Revision ID: a6dd633df5b9
Revises: c4835d002518
Create Date: 2026-09-10 17:31:17.214943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a6dd633df5b9'
down_revision: Union[str, Sequence[str], None] = 'c4835d002518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reference_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_tasks_reference_file_id', 'tasks', 'files', ['reference_file_id'], ['id'], ondelete='SET NULL')
    for table in ('task_assignment_details', 'task_lab_details', 'task_project_details'):
        op.execute(sa.text(f'UPDATE tasks SET reference_file_id = d.reference_file_id FROM {table} d WHERE tasks.id = d.task_id'))
        for fk in sa.inspect(op.get_bind()).get_foreign_keys(table):
            if fk['constrained_columns'] == ['reference_file_id']:
                op.drop_constraint(fk['name'], table, type_='foreignkey')
        op.drop_column(table, 'reference_file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for fk in sa.inspect(op.get_bind()).get_foreign_keys('tasks'):
        if fk['constrained_columns'] == ['reference_file_id']:
            op.drop_constraint(fk['name'], 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'reference_file_id')
    op.add_column('task_project_details', sa.Column('reference_file_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('task_project_details_ibfk_2'), 'task_project_details', 'files', ['reference_file_id'], ['id'], ondelete='SET NULL')
    op.add_column('task_lab_details', sa.Column('reference_file_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('task_lab_details_ibfk_3'), 'task_lab_details', 'files', ['reference_file_id'], ['id'], ondelete='SET NULL')
    op.add_column('task_assignment_details', sa.Column('reference_file_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('task_assignment_details_ibfk_2'), 'task_assignment_details', 'files', ['reference_file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
