"""empty message

Revision ID: c4835d002518
Revises: 285e883422a7
Create Date: 2026-09-10 17:28:43.698697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4835d002518'
down_revision: Union[str, Sequence[str], None] = '285e883422a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_assignment_details', sa.Column('reference_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_assignment_details', 'files', ['reference_file_id'], ['id'], ondelete='SET NULL')
    op.add_column('task_project_details', sa.Column('reference_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_project_details', 'files', ['reference_file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_project_details', type_='foreignkey')
    op.drop_column('task_project_details', 'reference_file_id')
    op.drop_constraint(None, 'task_assignment_details', type_='foreignkey')
    op.drop_column('task_assignment_details', 'reference_file_id')
    # ### end Alembic commands ###
